//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleChoiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int User_ID { get; set; }
        public int Test_ID { get; set; }
        public int User_Mark { get; set; }
    
        public virtual User User { get; set; }
        public virtual Test Test { get; set; }
    }
}
